name: "Sean's Photographs"
favicon: null
layout_spectrum: 0.49302
typography_spectrum: 0.5018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e1e1'
    - '#373737'
    - '#555555'
    - '#8f8f8f'
    - '#1c1c1c'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
