name: "Sean's Photographs"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.525210436200723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e1e1'
    - '#373737'
    - '#555555'
    - '#8f8f8f'
    - '#1c1c1c'
  brandStrength: 0.125
  lightness: 0.6088732173666358
  saturation: 0.9557074813637882
  rhythmicContrast: 0.744123914046213
purpose: []
